### ISSUE TITLE
auth0-jsのバージョンを上げるのバージョンを上げる

### ISSUE THREAD

**Issue by konchanSS** [SmartPhoneAppsProject/BookSeeker#12]
今のauth0-jsのバージョンが脆弱性あるとgithub側から警告されてます
脆弱性の内容を確認してバージョンを上げましょう
<img width="1007" alt="2018-02-18 15 27 00" src="https://user-images.githubusercontent.com/13659262/36349034-902a8baa-14c0-11e8-81b3-ae76f2ed48b2.png">

**Comment by konchanSS** [comment]
@kkenya @TatsuyaKitagawa @nomurakkooo

**Comment by konchanSS** [comment]
あれ、まだ表示されてるね

**Comment by konchanSS** [comment]
なんでだ

**Comment by kkenya** [comment]
依存パッケージとしてインストールされているので、auth0-js自体のアップデートは出来ませんでした
