### ISSUE TITLE
数回に一回JSON Parse errorが生じる

### ISSUE THREAD

**Issue by nomurakkooo** [SmartPhoneAppsProject/BookSeeker#14]
## 数回に一度以下のエラーが生じる
- リロードすると正しくパースされるが数回ごとにエラーが生じる
![image](https://user-images.githubusercontent.com/29516756/36350599-67c5d39a-14de-11e8-9e7a-e0e339b54f16.png)

**Comment by JinOketani** [comment]
@nomurakkooo これはたぶん推測だけどサーバー側の問題だと思う。Herokuの無料プランでは一定時間アクセスがないとサーバーが寝てしまうんだけど、Golangのコード実行速度がサーバーを起こす時間よりも早いためにおこるエラーだと考えられる。

**Comment by nomurakkooo** [comment]
なるほど。
その説濃厚そうだね。
サーバーが起きるトリガーとしてはリクエスト投げると起きるとか？

**Comment by kkenya** [comment]
リクエスト投げたときにHerokuが寝ててInternal Server Errorを返すみたいだから、クライアント側でOKが返ってこなかったらもう一度リクエスト投げるようにしよう
