### ISSUE TITLE
reduxを導入しよう！

### ISSUE THREAD

**Issue by nomuco** [SmartPhoneAppsProject/BookSeeker#83]
redux導入案件が多々発生している。
導入しよう

**Comment by konchanSS** [comment]
@nomurakkooo Reduxを導入するとこういうコードがこうなりますっていう例やメリットを説明するとGood

**Comment by kkenya** [comment]
- redux, reduxミドルウェアの導入
- ディレクトリ構成の変更(actions/reducers/components/constants)
